
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dw'
version: '0.1.0'
require-dbt-version: [">=1.6.2", "<2.0.0"]
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dw'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dw:
    # Config indicated by + and applies to all files under models/example/
    marts:
      +materialized: table
    staging:
      +bind: false
      +materialized: view
    metrics:
      +materialized: table
    client_data_requests:
      +materialized: view
    analysis:
      +materialized: view

vars:
  dw:
    adeid_start_date: "2022-03-01"
    discharge_filter_date: "2021-01-01"
    patient_event__discharge: "A03"
    patient_event__hospital_discharge: "HD"
    patient_event__hospital_admit: "HA"
    patient_event__discharge_disposition: "HOME"

    patient_institution_filter: [
      "united",
      "advantasure",
      "sinfonia",
      "humana"
    ]

    contact_institution_filter: [
      "united",
      "united_gap",
      "advantasure",
      "sinfonia",
      "humana",
      "wph_cares"
    ]

    patient_subscription_filter: [
      "united",
      "advantasure",
      "sinfonia",
      "chf_program",
      "rtm_chf"
    ]

    salesforce_enrollment_types: [
      "enrollment attempt #1",
      "enrollment attempt #2",
      "enrollment attempt #3",
      "enrollment attempt #4",
      "re-enrollment attempt"
    ]

    salesforce_pur_types: [
      "Provider Urgent Request Attempt #1",
      "Provider Urgent Request Attempt #2",
      "Provider Urgent Request Attempt #3"
    ]

    salesforce_invalid_phone_dispositions: [
      "line disconnected",
      "incorrect number",
      "no contact info"
    ]

    salesforce_patient_reached_dispositions: [
      "encounter scheduled",
      "encounter scheduled - warm transfer",
      "refused service",
      "refused service - re-attempt",
      "do not contact",
      "patient reached - no follow up action with patient",
      "patient reached - no mrp or map"
    ]

    salesforce_patient_scheduled_dispositions: [
      "encounter scheduled",
      "encounter scheduled - warm transfer"
    ]

    salesforce_map_provider_recipients: [
      "pcp",
      "non-pcp provider"
    ]

    salesforce_no_show_dispositions: [
      "lvm",
      "no answer",
      "line disconnected"
    ]

    salesforce_ignore_event_ids: [
      "00U4x0000087RhyEAE"
    ]

    salesforce_discharges_known_missing_ea1s: [
      "62109d0301d2b75a81604ff5"
    ]

    duplicate_patients_to_ignore: [
      "6262d19ba3a57a857fb39417",
      "6262d945a3a57a857fb5d534",
      "621967c521b65fc6d3137f1b",
      "6219671e21b65fc6d3137b5a",
      "621968f521b65fc6d31387a5",
      "617826d44ab7ef03feec96ca",
      "6219675e21b65fc6d3137ccf",
      "6262d463a3a57a857fb45e60",
      "61781dbb4ab7ef03fee6d341",
      "6262d2f4a3a57a857fb3f13f",
      "61782bb94ab7ef03fef1ffb2"
    ]

    map_finalized_status: "finalized"

    ineligible_opportunity_closure_status: [
      "Rejected",
      "Opt-out",
      "Ineligible"
    ]

    ineligible_opportunity_closure_type: [
      "patient-disabled-closure-reason",
      "patient-status-closure-reason",
      "hospital-admit-event-closure-reason",
      "home-discharge-event-closure-reason",
      "cancel-discharge-event-closure-reason"
    ]

    eligible_opportunity_closure_type: "no-op-closure-reason"

    eligible_opportunity_status: [
      "standby",
      "new",
      "open",
      "completed",
      "could not reach"
    ]

    eligible_enrollment_info_type: "circuit-enrollment-info"

    discharge_opportunity_trigger_type: "home-discharge-event-opportunity-trigger"

    us_states: [ "AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL",
                 "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH",
                 "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM",
                 "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC",
                 "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"      ]

    cureatr_user_institutions: [
    "cureatrpharmacy",
    "cureatr"
    ]

    follow_up_task_types: [
    "patient follow-up",
    "provider follow-up",
    "plan follow-up",
    "pharmacy follow-up"
    ]

    cmr_card_name_exclusions: ['WALMT','WRTHI','2485','9716','HTM4','JD68','JD77','PLRX1','PLRX6',
      'QMTM','AHF01','AHF02','LHP01','LPH01','CARE','IEH01','UHCMR','E3335','E3351','S3521','U3335','U3351'
    ]

    opportunity_id_tied_same_discharge_date: [
        '64429ca14833b9ea6b4ec74e',
        '64387ebd607abb918f7f1918',
        '63f543b4953814ffd42f88d5',
        '63f89c17953814ffd42f8fd2',
        '64d1256101e431a747a59bf6',
        '64c966f754fba80e1170f4e6',
        '6460119d4a2f74ea6e0b6c0c',
        '646304abad771b4b24061973'
    ]
