"""Generate one dbt exposure per delivered file, and check the generated file
has not drifted.

Without exposures, a file sent outside the company is invisible in the dbt DAG,
so `dbt ls --select +exposure:*` cannot answer "what does this PR change for
the people we send files to?". The drift check matters as much as the
generator: a stale generated file is worse than none, because it looks
authoritative.

Works offline from `target/manifest.json` (run `dbt parse` first; no warehouse
connection). Cross-checks each export against the manifest:
  - its source resolves to exactly one dbt model, seed, or snapshot (by alias);
  - every column it references (selected, filtered, windowed, tenant) is
    documented on that model -- the manifest only knows documented columns,
    so an undocumented column is treated as missing;
  - no two exposures share a name.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

import yaml

from file_export.config import ExportConfig, Recipient

HEADER = (
    "# GENERATED by `file-export exposures --write` from delivery/file-export/configs/.\n"
    "# Do not edit by hand: CI runs `--check` and fails when this file is stale.\n"
)
RESOURCE_TYPES = {"model", "seed", "snapshot"}


class ExposureError(ValueError):
    """The configs and the dbt manifest disagree. Lists every problem found."""


@dataclass(frozen=True)
class Resolved:
    name: str
    columns: set[str]


def load_manifest(path: Path) -> dict:
    if not path.exists():
        raise ExposureError(f"{path} not found -- run `dbt parse` first")
    return json.loads(path.read_text())


def resolve(manifest: dict, relation: str) -> Resolved:
    """Find the dbt node a relation name refers to, matching the table part
    against each node's alias (dbt's alias defaults to the model name) and,
    when that is ambiguous, the schema part against its configured schema."""
    parts = relation.split(".")
    table, schema = parts[-1].lower(), (parts[-2].lower() if len(parts) > 1 else None)
    candidates = [
        node
        for node in manifest["nodes"].values()
        if node["resource_type"] in RESOURCE_TYPES
        and (node.get("alias") or node["name"]).lower() == table
    ]
    if len(candidates) > 1 and schema:
        candidates = [
            n
            for n in candidates
            if (n["config"].get("schema") or n["schema"]).lower() == schema
        ]
    if not candidates:
        raise ExposureError(
            f"source {relation} matches no dbt model, seed, or snapshot"
        )
    if len(candidates) > 1:
        names = sorted(n["unique_id"] for n in candidates)
        raise ExposureError(f"source {relation} is ambiguous: {names}")
    node = candidates[0]
    return Resolved(name=node["name"], columns={c.lower() for c in node["columns"]})


def exposure_name(config: ExportConfig, recipient: Recipient, suffix: str) -> str:
    raw = f"export__{config.name}__{recipient.name}__{suffix}"
    return re.sub(r"[^a-z0-9_]", "_", raw.lower())


def build(configs: list[ExportConfig], manifest: dict) -> dict:
    """The exposures document. Raises ExposureError listing every problem."""
    exposures, problems = [], []
    for config in sorted(configs, key=lambda c: c.name):
        for recipient in config.recipients:
            where = f"export {config.name} / recipient {recipient.name}"
            relation = config.source_for(recipient)
            try:
                target = resolve(manifest, relation)
            except ExposureError as exc:
                problems.append(f"{where}: {exc}")
                continue
            missing = sorted(
                c
                for c in config.referenced_columns(recipient)
                if c.lower() not in target.columns
            )
            if missing:
                problems.append(
                    f"{where}: column(s) {missing} not documented on dbt model {target.name}"
                )
                continue

            formats = [o.format for o in config.outputs]
            for index, output in enumerate(config.outputs):
                suffix = (
                    output.format
                    if formats.count(output.format) == 1
                    else f"{output.format}_{index}"
                )
                owner = {"name": config.owner.name}
                if config.owner.email:
                    owner["email"] = config.owner.email
                exposures.append(
                    {
                        "name": exposure_name(config, recipient, suffix),
                        "label": f"{config.name} to {recipient.name} ({output.format})",
                        "type": "application",
                        "owner": owner,
                        "description": (
                            f"{config.kind.value} file export `{config.name}` delivered to "
                            f"`{recipient.name}` as `{output.path}`."
                        ),
                        "depends_on": [f"ref('{target.name}')"],
                        "meta": {
                            "export": config.name,
                            "kind": config.kind.value,
                            "recipient": recipient.name,
                            "path": output.path,
                            "format": output.format,
                            "schedule": recipient.schedule.cron
                            if recipient.schedule
                            else "unscheduled",
                        },
                    }
                )

    names = [e["name"] for e in exposures]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        problems.append(f"duplicate exposure names: {duplicates}")
    if problems:
        raise ExposureError("\n".join(problems))
    return {"version": 2, "exposures": exposures}


def render(document: dict) -> str:
    return HEADER + yaml.safe_dump(
        document, sort_keys=False, width=100, allow_unicode=True
    )


def generate(configs: list[ExportConfig], manifest_path: Path) -> str:
    return render(build(configs, load_manifest(manifest_path)))


def is_current(path: Path, expected: str) -> bool:
    return path.exists() and path.read_text() == expected
